name: Release

on:
  release:
    types:
      - published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Run test with agent
        run: ./gradlew -Pagent test

      - name: Metadata copy
        run: ./gradlew metadataCopy --task test --dir src/main/resources/META-INF/native-image

      - name: Compile native image
        run: ./gradlew nativeCompile check

      - name: Add Executable to release
        uses: softprops/action-gh-release@v1
        with:
          files: build/native/nativeCompile/GitMergePipeline
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
